version: '3.8'

volumes:
  gradle_cache:

services:
  autotests:
#    image: mcr.microsoft.com/playwright/java:v1.59.0-jammy
    # Или сборка из Dockerfile:
    build: .
    volumes:
      - ./src:/app/src
      - ./reports:/app/build/reports
      - gradle_cache:/root/.gradle/caches
    environment:
      - HEADLESS=true
      - TEST_ENV=staging
    working_dir: /app
#    command: [ "sh", "-c", "xvfb-run -a .\gradlew test --no-daemon" ]
    shm_size: 2gb
    init: true
